name 'kioskuser'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures kioskuser'
long_description 'Installs/Configures kioskuser'
version '0.1.0'
